version: '3.1'

services:
  backend:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=postgres
    # Uncomment next three lines to retain Postgres data
    #  - PGDATA=/var/lib/postgresql/data/pgdata
    #volumes:
    #  - ./pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
