#!/usr/bin/env bash
set -e
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )";
COMPOSE_FILE="$SCRIPT_DIR/../docker-compose.yml";
docker-compose \
  -f $COMPOSE_FILE \
  up \
  -d \
  backend;
direnv reload;
